FROM node:20.10.0 as build

WORKDIR /app/

COPY ./package*.json ./
COPY ./tsconfig*.json ./
COPY ./src/ ./src/
COPY ./vite.config.ts ./
COPY ./index.html ./

RUN npm install -g npm@10.2.3 && \
	npm ci --omit=dev && \
	npm run build

FROM nginx:1.24.0

WORKDIR /etc/nginx/

ADD ./docker/app/nginx.conf /etc/nginx/nginx.conf

COPY --from=build /app/dist/ /usr/share/nginx/html

EXPOSE 8080

# CMD nginx -g daemon off;
