services:
  app:
    build:
      context: ./docker/app/
      dockerfile: Dockerfile.dev
    tty: true
    stdin_open: true
    init: true
    environment:
      TZ: Asia/Tokyo
      CHOKIDAR_USEPOLLING: 1
      HOST: 0.0.0.0
    ports:
      - "6001:6001"
    working_dir: /app/
    volumes:
      - ./:/app/
